import SwiftUI

struct ConnectionManagerView: View {
    @EnvironmentObject var connectionManager: ConnectionManager
    @State private var showingAddConnection = false
    @State private var editingConnection: ConnectionConfig?
    @State private var searchText = ""
    @State private var selectedGroup: String?
    @State private var expandedConnections: Set<UUID> = []
    @State private var autoGeneratedQuery: String?
    
    var groups: [String?] {
        let allGroups = Set(connectionManager.connections.map { $0.groupName })
        return [nil] + allGroups.compactMap { $0 }.sorted()
    }
    
    var filteredConnections: [ConnectionConfig] {
        var connections = connectionManager.connections
        
        if let selectedGroup = selectedGroup {
            connections = connections.filter { $0.groupName == selectedGroup }
        }
        
        if !searchText.isEmpty {
            connections = connections.filter { connection in
                connection.name.localizedCaseInsensitiveContains(searchText) ||
                connection.host?.localizedCaseInsensitiveContains(searchText) == true
            }
        }
        
        return connections
    }
    
    var body: some View {
        HSplitView {
            VStack(spacing: 0) {
                VStack(spacing: 8) {
                    SearchField("搜索连接...", text: $searchText)
                    
                    ScrollView(.horizontal, showsIndicators: false) {
                        HStack(spacing: 8) {
                            ForEach(groups, id: \.self) { group in
                                Button(action: { selectedGroup = group }) {
                                    Text(group ?? "全部")
                                        .font(.caption)
                                        .padding(.horizontal, 12)
                                        .padding(.vertical, 6)
                                        .background(selectedGroup == group ? Color.accentColor : Color(NSColor.controlBackgroundColor))
                                        .foregroundColor(selectedGroup == group ? .white : .primary)
                                        .cornerRadius(6)
                                }
                                .buttonStyle(PlainButtonStyle())
                            }
                        }
                        .padding(.horizontal, 4)
                    }
                }
                .padding()
                
                Divider()
                
                ScrollView {
                    LazyVGrid(columns: [GridItem(.flexible(), spacing: 12)], spacing: 12) {
                        ForEach(filteredConnections) { connection in
                            ConnectionCard(
                                connection: connection,
                                isSelected: connectionManager.selectedConnection?.id == connection.id,
                                isExpanded: expandedConnections.contains(connection.id),
                                onSelect: { connect(to: connection) },
                                onToggleExpand: {
                                    if expandedConnections.contains(connection.id) {
                                        expandedConnections.remove(connection.id)
                                    } else {
                                        expandedConnections.insert(connection.id)
                                    }
                                },
                                onEdit: { editingConnection = connection },
                                onDelete: { deleteConnection(connection) },
                                onTableDoubleClick: { tableName in
                                    autoGeneratedQuery = "SELECT * FROM \(tableName) LIMIT 10"
                                }
                            )
                        }
                    }
                    .padding()
                }
                
                Divider()
                
                HStack {
                    Button(action: { showingAddConnection = true }) {
                        Label("添加连接", systemImage: "plus")
                    }
                    Spacer()
                    Text("\(filteredConnections.count) 个连接")
                        .font(.caption)
                        .foregroundColor(.secondary)
                }
                .padding()
            }
            .frame(minWidth: 250, idealWidth: 320)
            
            if let selectedConnection = connectionManager.selectedConnection,
               connectionManager.isConnected {
                QueryEditorView(
                    connection: selectedConnection,
                    initialQuery: autoGeneratedQuery
                )
                .frame(minWidth: 400)
            } else {
                VStack(spacing: 20) {
                    Image(systemName: "cylinder.split.1x2")
                        .font(.system(size: 64))
                        .foregroundColor(.secondary)
                    Text("选择一个连接以开始")
                        .font(.title2)
                        .foregroundColor(.secondary)
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity)
            }
        }
        .navigationTitle("CopyCat - 数据库管理")
        .toolbar {
            ToolbarItem(placement: .automatic) {
                if connectionManager.isConnected {
                    Button(action: { connectionManager.disconnect() }) {
                        Label("断开连接", systemImage: "xmark.circle.fill")
                            .foregroundColor(.red)
                    }
                }
            }
        }
        .sheet(isPresented: $showingAddConnection) {
            ConnectionFormView(connection: nil)
        }
        .sheet(item: $editingConnection) { connection in
            ConnectionFormView(connection: connection)
        }
        .frame(minWidth: 1000, minHeight: 600)
    }
    
    private func connect(to connection: ConnectionConfig) {
        Task {
            do {
                try await connectionManager.connect(to: connection)
            } catch {
                Logger.shared.error("连接失败: \(error)")
            }
        }
    }
    
    private func deleteConnection(_ connection: ConnectionConfig) {
        Task { @MainActor in
            let alert = NSAlert()
            alert.messageText = "确认删除连接"
            alert.informativeText = "确定要删除连接 \"\(connection.name)\" 吗？此操作无法撤销。"
            alert.alertStyle = .warning
            alert.addButton(withTitle: "取消")
            alert.addButton(withTitle: "删除")
            
            if alert.runModal() == .alertSecondButtonReturn {
                try? PasswordVault.shared.deletePassword(for: connection.id)
                connectionManager.deleteConnection(connection)
            }
        }
    }
}

struct SearchField: NSViewRepresentable {
    let placeholder: String
    @Binding var text: String
    
    init(_ placeholder: String, text: Binding<String>) {
        self.placeholder = placeholder
        self._text = text
    }
    
    func makeNSView(context: Context) -> NSSearchField {
        let searchField = NSSearchField(string: text)
        searchField.placeholderString = placeholder
        searchField.delegate = context.coordinator
        return searchField
    }
    
    func updateNSView(_ nsView: NSSearchField, context: Context) {
        nsView.stringValue = text
    }
    
    func makeCoordinator() -> Coordinator {
        Coordinator(self)
    }
    
    class Coordinator: NSObject, NSSearchFieldDelegate {
        let parent: SearchField
        
        init(_ parent: SearchField) {
            self.parent = parent
        }
        
        func controlTextDidChange(_ obj: Notification) {
            if let textField = obj.object as? NSTextField {
                parent.text = textField.stringValue
            }
        }
    }
}
